### ISSUE TITLE
Add ability to fix using `--fix` flag

### ISSUE THREAD

**Issue by bhumijgupta** [bhumijgupta/eslint-plugin-no-function-declare-after-return#2]
Create a fixer function to move the function declaration before return statement

Useful links
1. https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes

**Comment by TheGLander** [comment]
Hmm, I can do this feature, can you assign me to this?

**Comment by bhumijgupta** [comment]
Sure thing @TheGLander
